package lesson27_exception;

public class Test20 {
//NE PISAL //NE PISAL //NE PISAL //NE PISAL //NE PISAL //NE PISAL //NE PISAL //NE PISAL
//NE PISAL //NE PISAL //NE PISAL //NE PISAL //NE PISAL //NE PISAL //NE PISAL //NE PISAL

}

